services:
    sveltekit:
        build: .
        container_name: kanban-frontend
        ports:
            - "2001:3000"
        restart: unless-stopped
        environment:
            VITE_COMMIT_HASH: ${VITE_COMMIT_HASH}
            VITE_COMMIT_URL: ${VITE_COMMIT_URL}